### ISSUE TITLE
알림음 미출력 이슈

### ISSUE THREAD

**Issue by yyw10242** [yf-dev/chaosrat#10]
![image](https://github.com/yf-dev/chaosrat/assets/4463238/7cf39c35-4869-453f-ab10-b98bf563fc1e)
볼륨 설정과 관련하여 정확한 값을 입력해주어야 하는 것으로 확인 중.

**Comment by rishubil** [comment]
오류 발생한 채팅 오버레이 URL을 올려주실 수 있나요?

**Comment by yyw10242** [comment]
https://chaosrat.update.sh/chat?chzzkChannelId=11a859e32ce8d8b4500d21ee9e88ab31&twitchChannel=yyw10242&theme=simple&maxChatSize=15&soundEffectType=beep
