### ISSUE TITLE
url 출력 이슈

### ISSUE THREAD

**Issue by naznizu** [yf-dev/chaosrat#11]
1. url 주소가 짤리는 현상

입력한 링크
![url1](https://github.com/yf-dev/chaosrat/assets/79119143/ef059539-3b5a-4f19-9e26-20bbe9ccb697)

오버레이에 나오는 링크
![url2](https://github.com/yf-dev/chaosrat/assets/79119143/e60357a1-2d85-488b-a288-9ae46e321af2)

2. 링크 대체 텍스트 기능 설정
url 입력시 "[링크]" 로 출력

**Comment by rishubil** [comment]
> 1. url 주소가 짤리는 현상

커밋 c7648add68b82f63e467afec26f958311bd459e2 에서 수정했습니다.

> 2. 링크 대체 텍스트 기능 설정
>    url 입력시 "[링크]" 로 출력

이 기능은 특정 정규표현식에 일치하는 문자열을 다른 문자열로 대체하는 방식으로 구현하는 것이 더 적절해 보입니다.
해당 이슈는 별도 이슈로 분리해서 관리하고, 이 이슈는 닫겠습니다.
