### ISSUE TITLE
디시콘 출력 문제

### ISSUE THREAD

**Issue by naznizu** [yf-dev/chaosrat#3]
디시콘 이름이 같고 뒤에 숫자가 붙는경우

숫자가 붙지 않은 디시콘만 출력되는 문제가 있네요

디시콘이 "~안녕 ~안녕1 ~안녕2" 가 있을 경우 "~안녕1 ~안녕2"를 입력해도

"~안녕" 디시콘만 출력되고 숫자는 텍스트로 표시됩니다

![1234](https://github.com/yf-dev/chaosrat/assets/79119143/c6cdea4e-067b-4dd6-a8d8-d6c64499c787)

**Comment by rishubil** [comment]
버그 제보 감사합니다.
최신 버전에서 정상적으로 표시될 수 있도록 수정했습니다.
